# Generated by Django 4.0.2 on 2022-02-23 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aqpgapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='mark',
            field=models.IntegerField(default=4),
        ),
    ]
