# Generated by Django 4.0.2 on 2022-02-23 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aqpgapp', '0002_alter_question_mark'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='qn',
            field=models.CharField(max_length=1000),
        ),
    ]
