# Generated by Django 4.0.2 on 2022-02-23 17:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aqpgapp', '0003_alter_question_qn'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Question',
        ),
    ]
