# Generated by Django 4.0.2 on 2022-02-24 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_question', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dbms',
            name='marks',
        ),
        migrations.AddField(
            model_name='dbms',
            name='marks2',
            field=models.IntegerField(default=4),
        ),
        migrations.AddField(
            model_name='dbms',
            name='marks4',
            field=models.IntegerField(default=4),
        ),
    ]
