# Generated by Django 4.0.2 on 2022-02-24 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_question', '0002_remove_dbms_marks_dbms_marks2_dbms_marks4'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dbms',
            name='marks2',
            field=models.IntegerField(default=2),
        ),
    ]
