# Generated by Django 4.0.2 on 2022-02-25 04:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project_question', '0003_alter_dbms_marks2'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dbms',
            old_name='marks4',
            new_name='marks',
        ),
        migrations.RemoveField(
            model_name='dbms',
            name='marks2',
        ),
    ]
